// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3PJM5mk76qT4T_icfwfv5-Tlm0upaHbE',
    appId: '1:468349231006:web:d3c48646cc9d9fecdcc08f',
    messagingSenderId: '468349231006',
    projectId: 'nineheartz-761bf',
    authDomain: 'nineheartz-761bf.firebaseapp.com',
    storageBucket: 'nineheartz-761bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFHPcTM7-z24V9cGlrej9P0WH29NWdLE',
    appId: '1:468349231006:android:059f82433dd4b0e2dcc08f',
    messagingSenderId: '468349231006',
    projectId: 'nineheartz-761bf',
    storageBucket: 'nineheartz-761bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD67B5lImrjOccjWOoBz5er22l29ND35L8',
    appId: '1:468349231006:ios:ad50fb3e943fcf1adcc08f',
    messagingSenderId: '468349231006',
    projectId: 'nineheartz-761bf',
    storageBucket: 'nineheartz-761bf.appspot.com',
    iosClientId: '468349231006-c2kjf1bs97n737ia4pc9as648focqml7.apps.googleusercontent.com',
    iosBundleId: 'com.example.nineheartzAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD67B5lImrjOccjWOoBz5er22l29ND35L8',
    appId: '1:468349231006:ios:ad50fb3e943fcf1adcc08f',
    messagingSenderId: '468349231006',
    projectId: 'nineheartz-761bf',
    storageBucket: 'nineheartz-761bf.appspot.com',
    iosClientId: '468349231006-c2kjf1bs97n737ia4pc9as648focqml7.apps.googleusercontent.com',
    iosBundleId: 'com.example.nineheartzAssignment',
  );
}
